# Purpose:
#   Automatically calculates the next semantic version and creates a tag on the repository
#   when a PR is merged.

name: Increment Tag Version on Merge
on:
  push:
jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate next version
        id: semver
        run: |
          current_version=$(git describe --tags --abbrev=0)
          next_version=$(conventional-recommended-bump -p angular)
          echo "::set-output name=version::v${next_version}"
      
      - name: Create tag
        # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: |
          version="${{ steps.semver.outputs.version }}"
          git tag "${version}"
          git push origin "${version}"
